export const FETCH_PRODUCTS_BEGIN = "FETCH_PRODUCTS_BEGIN";
export const FETCH_PRODUCTS_SUCCESS =
    "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAILURE =
    "FETCH_PRODUCTS_FAILURE";
export const ADD_TO_CART =
    "ADD_TO_CART";
export const REMOVE_FROM_CART =
    "REMOVE_FROM_CART";
export const ADD_PRICES =
    "ADD_PRICES";
export const DETRACT_PRICE =
    "DETRACT_PRICE";